In [1]:
import pandas as pd
import json

# Load the JSON data
with open('/content/sample_output.json', 'r') as json_file:
    data = json.load(json_file)

# Convert the JSON data to a DataFrame
df = pd.json_normalize(data)

# Save the DataFrame to a CSV file
df.to_csv('data.csv', index=False)

print("JSON has been converted to CSV successfully.")

JSON has been converted to CSV successfully.

In [2]:
data = pd.read_csv('/content/data.csv')
data.head()

,resource_state,name,distance,moving_time,elapsed_time,total_elevation_gain,type,sport_type,workout_type,id,...,similar_activities.max_average_speed,similar_activities.pr_rank,similar_activities.frequency_milestone,similar_activities.trend.speeds,similar_activities.trend.current_activity_index,similar_activities.trend.min_speed,similar_activities.trend.mid_speed,similar_activities.trend.max_speed,similar_activities.trend.direction,similar_activities.resource_state
0,3,motivated,12395.3,3313,3441,126.0,Run,Run,0,12653066414,...,3.922365,NaN,5,"[3.9223649719745493, 3.9151144337792423, 3.909...",4,3.714914,3.815822,3.922365,-1,2

In [3]:
pd.options.display.max_columns = None  # This will display all columns
pd.options.display.width = 1000        # Adjust the display width if necessary

# Display the DataFrame
data.head()

,resource_state,name,distance,moving_time,elapsed_time,total_elevation_gain,type,sport_type,workout_type,id,start_date,start_date_local,timezone,utc_offset,location_city,location_state,location_country,achievement_count,kudos_count,comment_count,athlete_count,photo_count,trainer,commute,manual,private,visibility,flagged,gear_id,start_latlng,end_latlng,average_speed,max_speed,average_cadence,average_watts,max_watts,weighted_average_watts,kilojoules,device_watts,has_heartrate,average_heartrate,max_heartrate,heartrate_opt_out,display_hide_heartrate_option,elev_high,elev_low,upload_id,upload_id_str,external_id,from_accepted_tag,pr_count,total_photo_count,has_kudoed,suffer_score,description,calories,perceived_exertion,prefer_perceived_exertion,segment_efforts,splits_metric,splits_standard,laps,best_efforts,stats_visibility,hide_from_home,device_name,embed_token,available_zones,athlete.id,athlete.resource_state,map.id,map.polyline,map.resource_state,map.summary_polyline,gear.id,gear.primary,gear.name,gear.nickname,gear.resource_state,gear.retired,gear.distance,gear.converted_distance,photos.primary.unique_id,photos.primary.urls.600,photos.primary.urls.100,photos.primary.source,photos.primary.media_type,photos.use_primary_photo,photos.count,similar_activities.effort_count,similar_activities.average_speed,similar_activities.min_average_speed,similar_activities.mid_average_speed,similar_activities.max_average_speed,similar_activities.pr_rank,similar_activities.frequency_milestone,similar_activities.trend.speeds,similar_activities.trend.current_activity_index,similar_activities.trend.min_speed,similar_activities.trend.mid_speed,similar_activities.trend.max_speed,similar_activities.trend.direction,similar_activities.resource_state
0,3,motivated,12395.3,3313,3441,126.0,Run,Run,0,12653066414,2024-10-14T12:45:27Z,2024-10-14T08:45:27Z,(GMT-05:00) America/New_York,-14400.0,NaN,NaN,NaN,1,16,0,1,0,False,False,False,False,everyone,False,g19908276,"[42.34635374508798, -71.1066878400743]","[42.345272647216916, -71.10637620091438]",3.741,7.895,87.8,335.2,581,344,1110.4,True,True,154.1,177.0,False,True,67.2,-5.2,13490417556,13490417556,garmin_ping_377684029061,False,0,2,False,87.0,"back to 7mi base runs, track tomorrow, healthy...",801.0,NaN,False,"[{'id': 3280904627397250524, 'resource_state':...","[{'distance': 1001.3, 'elapsed_time': 281, 'el...","[{'distance': 1609.8, 'elapsed_time': 449, 'el...","[{'id': 44404107689, 'resource_state': 2, 'nam...","[{'id': 53798507403, 'resource_state': 2, 'nam...","[{'type': 'heart_rate', 'visibility': 'everyon...",False,Garmin Forerunner 255S,065a5b253a10ef582637d1ccd43bf9b3390131de,"['heartrate', 'pace', 'power']",57248538,1,a12653066414,uwmaGx__qLr@{@FBF^DFP?LAzAm@R?JFLVd@lCX~@d@tDF...,3,uwmaGx__qLr@{@FBF^DFP?hBo@R?JFLVd@lCX~@d@tDFLH...,g19908276,False,ASICS Novablast 4,NaN,2,False,33371,20.7,530593C3-8ADD-46F6-A1AD-342855E9E3DA,https://dgtzuqphqg23d.cloudfront.net/-VjHC2kal...,https://dgtzuqphqg23d.cloudfront.net/-VjHC2kal...,1,1,True,2,5,3.833684,3.714914,3.815822,3.922365,NaN,5,"[3.9223649719745493, 3.9151144337792423, 3.909...",4,3.714914,3.815822,3.922365,-1,2

In [4]:
columns_to_drop = [
    "utc_offset", "heartrate_opt_out", "display_hide_heartrate_option",
    "from_accepted_tag", "has_kudoed", "description", "segment_efforts",
    "splits_metric", "splits_standard", "laps", "best_efforts",
    "stats_visibility", "hide_from_home", "available_zones",
    "athlete.resource_state", "map.id", "map.polyline", "map.resource_state",
    "map.summary_polyline", "gear.id", "gear.nickname", "gear.resource_state",
    "gear.retired", "gear.converted_distance", "photos.primary.unique_id",
    "photos.primary.urls.600", "photos.primary.urls.100", "photos.primary.source",
    "photos.primary.media_type", "photos.use_primary_photo", "photos.count",
    "similar_activities.trend.speeds", "similar_activities.trend.current_activity_index",
    "similar_activities.trend.min_speed", "similar_activities.trend.mid_speed",
    "similar_activities.trend.max_speed", "similar_activities.trend.direction",
    "similar_activities.resource_state"
]

# Drop the specified columns
data = data.drop(columns=columns_to_drop)

# Display the resulting DataFrame
data.head()

,resource_state,name,distance,moving_time,elapsed_time,total_elevation_gain,type,sport_type,workout_type,id,start_date,start_date_local,timezone,location_city,location_state,location_country,achievement_count,kudos_count,comment_count,athlete_count,photo_count,trainer,commute,manual,private,visibility,flagged,gear_id,start_latlng,end_latlng,average_speed,max_speed,average_cadence,average_watts,max_watts,weighted_average_watts,kilojoules,device_watts,has_heartrate,average_heartrate,max_heartrate,elev_high,elev_low,upload_id,upload_id_str,external_id,pr_count,total_photo_count,suffer_score,calories,perceived_exertion,prefer_perceived_exertion,device_name,embed_token,athlete.id,gear.primary,gear.name,gear.distance,similar_activities.effort_count,similar_activities.average_speed,similar_activities.min_average_speed,similar_activities.mid_average_speed,similar_activities.max_average_speed,similar_activities.pr_rank,similar_activities.frequency_milestone
0,3,motivated,12395.3,3313,3441,126.0,Run,Run,0,12653066414,2024-10-14T12:45:27Z,2024-10-14T08:45:27Z,(GMT-05:00) America/New_York,NaN,NaN,NaN,1,16,0,1,0,False,False,False,False,everyone,False,g19908276,"[42.34635374508798, -71.1066878400743]","[42.345272647216916, -71.10637620091438]",3.741,7.895,87.8,335.2,581,344,1110.4,True,True,154.1,177.0,67.2,-5.2,13490417556,13490417556,garmin_ping_377684029061,0,2,87.0,801.0,NaN,False,Garmin Forerunner 255S,065a5b253a10ef582637d1ccd43bf9b3390131de,57248538,False,ASICS Novablast 4,33371,5,3.833684,3.714914,3.815822,3.922365,NaN,5

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 65 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   resource_state                          1 non-null      int64
 1   name                                    1 non-null      object
 2   distance                                1 non-null      float64
 3   moving_time                             1 non-null      int64
 4   elapsed_time                            1 non-null      int64
 5   total_elevation_gain                    1 non-null      float64
 6   type                                    1 non-null      object
 7   sport_type                              1 non-null      object
 8   workout_type                            1 non-null      int64
 9   id                                      1 non-null      int64
 10  start_date                              1 non-null      object
 11  start_date_local                        1 non-null      object
 12  timezone                                1 non-null      object
 13  location_city                           0 non-null      float64
 14  location_state                          0 non-null      float64
 15  location_country                        0 non-null      float64
 16  achievement_count                       1 non-null      int64
 17  kudos_count                             1 non-null      int64
 18  comment_count                           1 non-null      int64
 19  athlete_count                           1 non-null      int64
 20  photo_count                             1 non-null      int64
 21  trainer                                 1 non-null      bool
 22  commute                                 1 non-null      bool
 23  manual                                  1 non-null      bool
 24  private                                 1 non-null      bool
 25  visibility                              1 non-null      object
 26  flagged                                 1 non-null      bool
 27  gear_id                                 1 non-null      object
 28  start_latlng                            1 non-null      object
 29  end_latlng                              1 non-null      object
 30  average_speed                           1 non-null      float64
 31  max_speed                               1 non-null      float64
 32  average_cadence                         1 non-null      float64
 33  average_watts                           1 non-null      float64
 34  max_watts                               1 non-null      int64
 35  weighted_average_watts                  1 non-null      int64
 36  kilojoules                              1 non-null      float64
 37  device_watts                            1 non-null      bool
 38  has_heartrate                           1 non-null      bool
 39  average_heartrate                       1 non-null      float64
 40  max_heartrate                           1 non-null      float64
 41  elev_high                               1 non-null      float64
 42  elev_low                                1 non-null      float64
 43  upload_id                               1 non-null      int64
 44  upload_id_str                           1 non-null      int64
 45  external_id                             1 non-null      object
 46  pr_count                                1 non-null      int64
 47  total_photo_count                       1 non-null      int64
 48  suffer_score                            1 non-null      float64
 49  calories                                1 non-null      float64
 50  perceived_exertion                      0 non-null      float64
 51  prefer_perceived_exertion               1 non-null      bool
 52  device_name                             1 non-null      object
 53  embed_token                             1 non-null      object
 54  athlete.id                              1 non-null      int64
 55  gear.primary                            1 non-null      bool
 56  gear.name                               1 non-null      object
 57  gear.distance                           1 non-null      int64
 58  similar_activities.effort_count         1 non-null      int64
 59  similar_activities.average_speed        1 non-null      float64
 60  similar_activities.min_average_speed    1 non-null      float64
 61  similar_activities.mid_average_speed    1 non-null      float64
 62  similar_activities.max_average_speed    1 non-null      float64
 63  similar_activities.pr_rank              0 non-null      float64
 64  similar_activities.frequency_milestone  1 non-null      int64
dtypes: bool(9), float64(22), int64(20), object(14)
memory usage: 585.0+ bytes

In [6]:
data['start_date'] = pd.to_datetime(data['start_date'])
data['start_date_local'] = pd.to_datetime(data['start_date_local'])

# Display the DataFrame to verify the changes
data.head()

,resource_state,name,distance,moving_time,elapsed_time,total_elevation_gain,type,sport_type,workout_type,id,start_date,start_date_local,timezone,location_city,location_state,location_country,achievement_count,kudos_count,comment_count,athlete_count,photo_count,trainer,commute,manual,private,visibility,flagged,gear_id,start_latlng,end_latlng,average_speed,max_speed,average_cadence,average_watts,max_watts,weighted_average_watts,kilojoules,device_watts,has_heartrate,average_heartrate,max_heartrate,elev_high,elev_low,upload_id,upload_id_str,external_id,pr_count,total_photo_count,suffer_score,calories,perceived_exertion,prefer_perceived_exertion,device_name,embed_token,athlete.id,gear.primary,gear.name,gear.distance,similar_activities.effort_count,similar_activities.average_speed,similar_activities.min_average_speed,similar_activities.mid_average_speed,similar_activities.max_average_speed,similar_activities.pr_rank,similar_activities.frequency_milestone
0,3,motivated,12395.3,3313,3441,126.0,Run,Run,0,12653066414,2024-10-14 12:45:27+00:00,2024-10-14 08:45:27+00:00,(GMT-05:00) America/New_York,NaN,NaN,NaN,1,16,0,1,0,False,False,False,False,everyone,False,g19908276,"[42.34635374508798, -71.1066878400743]","[42.345272647216916, -71.10637620091438]",3.741,7.895,87.8,335.2,581,344,1110.4,True,True,154.1,177.0,67.2,-5.2,13490417556,13490417556,garmin_ping_377684029061,0,2,87.0,801.0,NaN,False,Garmin Forerunner 255S,065a5b253a10ef582637d1ccd43bf9b3390131de,57248538,False,ASICS Novablast 4,33371,5,3.833684,3.714914,3.815822,3.922365,NaN,5

In [7]:
# List of boolean columns to convert
boolean_columns = ['trainer', 'commute', 'manual', 'private', 'flagged',
                   'device_watts', 'has_heartrate', 'prefer_perceived_exertion',
                   'gear.primary']

# Convert boolean columns to 0 and 1
data[boolean_columns] = data[boolean_columns].astype(int)

# Display the updated DataFrame to verify the changes
print(data[boolean_columns].head())

   trainer  commute  manual  private  flagged  device_watts  has_heartrate  prefer_perceived_exertion  gear.primary
0        0        0       0        0        0             1              1                          0             0

In [8]:
# Calculate total elevation change
data['elevation_change'] = data['elev_high'] - data['elev_low']

# Display the DataFrame to verify the new column
print(data[['elev_high', 'elev_low', 'elevation_change']].head())

   elev_high  elev_low  elevation_change
0       67.2      -5.2              72.4

In [9]:
# Extract time features from 'start_date_local'
data['day_of_week'] = data['start_date_local'].dt.day_name()  # Get the day name (e.g., Monday)
data['hour'] = data['start_date_local'].dt.hour               # Get the hour of the day
data['month'] = data['start_date_local'].dt.month_name()      # Get the month name (e.g., October)

# Display the DataFrame to verify the new columns
print(data[['start_date_local', 'day_of_week', 'hour', 'month']].head())

           start_date_local day_of_week  hour    month
0 2024-10-14 08:45:27+00:00      Monday     8  October

In [ ]:
import pandas as pd
from flask import Flask, request, jsonify
import os
from google.cloud import storage

app = Flask(__name__)

def download_file(bucket_name, source_blob_name, destination_file_name):
    """Download a file from GCP Storage."""
    storage_client = storage.Client()
    bucket = storage_client.bucket(bucket_name)
    blob = bucket.blob(source_blob_name)
    blob.download_to_filename(destination_file_name)

def upload_file(bucket_name, destination_blob_name, source_file_name):
    """Upload a file to GCP Storage."""
    storage_client = storage.Client()
    bucket = storage_client.bucket(bucket_name)
    blob = bucket.blob(destination_blob_name)
    blob.upload_from_filename(source_file_name)

def transform_data(input_path, output_path):
    # Transformations from the uploaded Jupyter notebook
    # Load the data
    data = json.load(json_file)

    # Convert the JSON data to a DataFrame
    df = pd.json_normalize(data)

    # Save the DataFrame to a CSV file
    df.to_csv('data.csv', index=False)
    data = pd.read_csv('/content/data.csv')
    columns_to_drop = [
    "utc_offset", "heartrate_opt_out", "display_hide_heartrate_option",
    "from_accepted_tag", "has_kudoed", "description", "segment_efforts",
    "splits_metric", "splits_standard", "laps", "best_efforts",
    "stats_visibility", "hide_from_home", "available_zones",
    "athlete.resource_state", "map.id", "map.polyline", "map.resource_state",
    "map.summary_polyline", "gear.id", "gear.nickname", "gear.resource_state",
    "gear.retired", "gear.converted_distance", "photos.primary.unique_id",
    "photos.primary.urls.600", "photos.primary.urls.100", "photos.primary.source",
    "photos.primary.media_type", "photos.use_primary_photo", "photos.count",
    "similar_activities.trend.speeds", "similar_activities.trend.current_activity_index",
    "similar_activities.trend.min_speed", "similar_activities.trend.mid_speed",
    "similar_activities.trend.max_speed", "similar_activities.trend.direction",
    "similar_activities.resource_state"]

    # Drop the specified columns
    data = data.drop(columns=columns_to_drop)
    data['start_date'] = pd.to_datetime(data['start_date'])
    data['start_date_local'] = pd.to_datetime(data['start_date_local'])
    boolean_columns = ['trainer', 'commute', 'manual', 'private', 'flagged',
                   'device_watts', 'has_heartrate', 'prefer_perceived_exertion',
                   'gear.primary']

    # Convert boolean columns to 0 and 1
    data[boolean_columns] = data[boolean_columns].astype(int)
    data['elevation_change'] = data['elev_high'] - data['elev_low']
    data['day_of_week'] = data['start_date_local'].dt.day_name()  # Get the day name (e.g., Monday)
    data['hour'] = data['start_date_local'].dt.hour               # Get the hour of the day
    data['month'] = data['start_date_local'].dt.month_name()      # Get the month name (e.g., October)



@app.route('/', methods=['POST'])
def main():
    """Main entry point for the Cloud Run function."""
    request_json = request.get_json()
    bucket_name = request_json['bucket_name']
    source_blob_name = request_json['source_blob_name']
    destination_blob_name = request_json['destination_blob_name']

    # File paths
    input_path = '/tmp/input.csv'
    output_path = '/tmp/output.csv'

    # Download the file from GCP Storage
    download_file(bucket_name, source_blob_name, input_path)

    # Perform the transformation
    transform_data(input_path, output_path)

    # Upload the transformed file back to GCP Storage
    upload_file(bucket_name, destination_blob_name, output_path)

    return jsonify({'status': 'success'}), 200

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=int(os.environ.get('PORT', 8080)))